# Ignore Travis CI and Appveyor so accurate GPU coverage is reported by GitLab.
codecov:
  ci:
    - !appveyor
    - !travis

coverage:
  range: 50..90
  round: down
  precision: 2

  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: auto
        threshold: 20%
