name = "OceanDispatch"
uuid = "e3bcbfb0-e86c-11e8-3e0d-655cddada36f"
authors = ["Ali Ramadhan <ali.hh.ramadhan@gmail.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
