env:
  CUDA_VISIBLE_DEVICES: 3

steps:
  - label: ":rabbit2: unit tests"
    commands:
      - "julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'"
      - "julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: tartarus
    env:
      TEST_GROUP: "unit"

  - label: ":dolphin: model tests"
    commands:
      - "julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'"
      - "julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: tartarus
    env:
      TEST_GROUP: "model"

  - label: ":whale: simulation tests"
    commands:
      - "julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'"
      - "julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: tartarus
    env:
      TEST_GROUP: "simulation"
 
  - label: ":camel: regression tests"
    commands:
      - "julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'"
      - "julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: tartarus
    env:
      TEST_GROUP: "regression"

  - label: ":gorilla: scripts"
    commands:
      - "julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'"
      - "julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: tartarus
    env:
      TEST_GROUP: "scripts"

  - label: ":sauropod: convergence tests"
    commands:
      - "julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'"
      - "julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: tartarus
    env:
      TEST_GROUP: "convergence"

