env:
  CUDA_VISIBLE_DEVICES: 3

steps:
  - label: ":rabbit2: unit tests"
    env:
      TEST_GROUP: "unit"
    commands:
      - "wget https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.2-linux-x86_64.tar.gz"
      - "tar xf julia-1.4.2-linux-x86_64.tar.gz"
      - "./julia-1.4.2/bin/julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'"
      - "./julia-1.4.2/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: tartarus


  - label: ":dolphin: model tests"
    env:
      TEST_GROUP: "model"
    commands:
      - "wget https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.2-linux-x86_64.tar.gz"
      - "tar xf julia-1.4.2-linux-x86_64.tar.gz"
      - "./julia-1.4.2/bin/julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'"
      - "./julia-1.4.2/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: tartarus

  - label: ":whale: simulation tests"
    env:
      TEST_GROUP: "simulation"
    commands:
      - "wget https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.2-linux-x86_64.tar.gz"
      - "tar xf julia-1.4.2-linux-x86_64.tar.gz"
      - "./julia-1.4.2/bin/julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'"
      - "./julia-1.4.2/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: tartarus
 
  - label: ":camel: regression tests"
    env:
      TEST_GROUP: "regression"
    commands:
      - "wget https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.2-linux-x86_64.tar.gz"
      - "tar xf julia-1.4.2-linux-x86_64.tar.gz"
      - "./julia-1.4.2/bin/julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'"
      - "./julia-1.4.2/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: tartarus

  - label: ":gorilla: scripts"
    env:
      TEST_GROUP: "scripts"
    commands:
      - "wget https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.2-linux-x86_64.tar.gz"
      - "tar xf julia-1.4.2-linux-x86_64.tar.gz"
      - "./julia-1.4.2/bin/julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'"
      - "./julia-1.4.2/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
    agents:
      queue: tartarus

  # - label: ":sauropod: convergence tests"
  #   env:
  #     TEST_GROUP: "convergence"
  #   commands:
  #     - "wget https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.2-linux-x86_64.tar.gz"
  #     - "tar xf julia-1.4.2-linux-x86_64.tar.gz"
  #     - "./julia-1.4.2/bin/julia --color=yes --project -e 'using Pkg; Pkg.instantiate()'"
  #     - "./julia-1.4.2/bin/julia --color=yes --project -e 'using Pkg; Pkg.test()'"
  #   agents:
  #     queue: tartarus

  - label: ":owl: documentation"
    commands:
      - "wget https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.2-linux-x86_64.tar.gz"
      - "tar xf julia-1.4.2-linux-x86_64.tar.gz"
      - "./julia-1.4.2/bin/julia --color=yes --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'"
      - "./julia-1.4.2/bin/julia --color=yes --project=docs/ docs/make.jl"
    agents:
      queue: tartarus
